"""empty message

Revision ID: df82008ebb35
Revises: 4ebb05fb377b
Create Date: 2018-05-19 23:51:40.245011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df82008ebb35'
down_revision = '4ebb05fb377b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.String(length=100), nullable=True))
    op.drop_constraint('messages_text_key', 'messages', type_='unique')
    op.drop_column('messages', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('text', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('messages_text_key', 'messages', ['text'])
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###
